# Packaging
quarkus.package.jar.type=legacy-jar
# HTTP
quarkus.http.root-path=/mysabr/api
quarkus.http.port=8082
quarkus.http.host=0.0.0.0
# Database (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=mysabruser
quarkus.datasource.password=mysabrpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mysabrdb

# Local application configuration
app.local.stack.enabled=true
app.local.stack.endpoint=http://localhost:4566
app.local.stack.aws.credentials.accessKeyId=test
app.local.stack.aws.credentials.secretAccessKey=test

# JWT configuration
app.jwt.issuer=mysabr-auth-api-issuer
app.jwt.secret=MYS@br123!@#
app.jwt.access.token.expires.in.hrs=24
app.jwt.remember.me.token.expires.in.hrs=720

# AWS configurations
aws.region=us-east-1
aws.eventbridge.bus.name=mysabr-event-bus

# Logging
quarkus.log.level=DEBUG

# JSON Serialization
quarkus.jackson.fail-on-unknown-properties=true
quarkus.jackson.accept-case-insensitive-enums=true

# Redis
redis.host=localhost
redis.port=6379

# OpenAPI / Swagger UI configuration
quarkus.smallrye-openapi.enable=true
quarkus.smallrye-openapi.path=/mysabr/openapi
quarkus.swagger-ui.path=/mysabr/swagger-ui
quarkus.swagger-ui.always-include=true
